### ISSUE TITLE
HttpVersion deserialization problem

### ISSUE THREAD

**Issue by OneCyrus** [dkackman/FakeHttp#2]
FakeHttp throws a deserialization exception with HttpVersion

`Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Version' because the type requires a JSON string value to deserialize correctly.
To fix this error either change the JSON to a JSON string value or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'HttpVersion.Major', line 3, position 12.`

**Comment by dkackman** [comment]
Can you provide an runnable example of how this is arising? This class https://github.com/dkackman/FakeHttp/blob/master/FakeHttp.NetStandard/VersionConverter.cs is supposed to deal with serialization of the HttpVersion property so something is different in your code or setup.

**Comment by OneCyrus** [comment]
ah ok I see, there's only a serialization converter but deserialization is not implemented.

but according to this https://stackoverflow.com/questions/13170386/why-system-version-in-json-string-does-not-deserialize-correctly#comment88131463_13177340

JsonConvert doesn't require special converters for version anymore. I just removed the JsonConverter in FakeHttp's serialization and it started to work again.

**Comment by OneCyrus** [comment]
thanks @dkackman for merging. any chance for an updated nuget package?

**Comment by dkackman** [comment]
@OneCyrus  Give this one a try. I revved the major version as I had added some features quite some time ago but never published them,

https://www.nuget.org/packages/Dkackman.FakeHttp/3.0.0
